<a href="https://colab.research.google.com/github/UniVR-DH/DKR-course/blob/main/L17-WikiData/example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SPARQL Queries for WikiData

In [1]:
!pip install -q sparqlwrapper    #install SPARQLwrapper

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 615.4/615.4 kB 12.8 MB/s eta 0:00:00

In [3]:
from SPARQLWrapper import SPARQLWrapper, JSON, XML, RDF
import pandas as pd

In [6]:
sparql = SPARQLWrapper("https://query.wikidata.org/sparql") #determine SPARQL endpoint
sparql.setReturnFormat(JSON) #determine the output format

In [21]:
#SPARQL query to be executed
sparql.setQuery("""
PREFIX wd:    <http://www.wikidata.org/entity/>
PREFIX wdt:   <http://www.wikidata.org/prop/direct/>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?author ?authorName ?birthPlace
WHERE {
  ?author wdt:P31 wd:Q36180 ;          # instance of writer
          rdfs:label ?authorName ;
          wdt:P19 ?birthPlace .       # place of birth
          ?birthPlace wdt:P31/wdt:P279* wd:Q515 . # place is an instance or a subclass of city

  FILTER (lang(?authorName) = "en")
}
ORDER BY ?authorName
""")

sparql.setReturnFormat(JSON)   # Return format is JSON
results = sparql.query().convert()   # execute SPARQL query and write result to "results"

In [22]:
len(results['results']['bindings'])

6

In [23]:
results_df = pd.json_normalize(results['results']['bindings'])
results_df[['author.value', 'authorName.value', 'birthPlace.value']]

,author.value,authorName.value,birthPlace.value
0,http://www.wikidata.org/entity/Q125947998,Seniha Bedri Göknil,http://www.wikidata.org/entity/Q406
1,http://www.wikidata.org/entity/Q125947998,Seniha Bedri Göknil,http://www.wikidata.org/entity/Q406
2,http://www.wikidata.org/entity/Q125947998,Seniha Bedri Göknil,http://www.wikidata.org/entity/Q406
3,http://www.wikidata.org/entity/Q125947998,Seniha Bedri Göknil,http://www.wikidata.org/entity/Q406
4,http://www.wikidata.org/entity/Q125947998,Seniha Bedri Göknil,http://www.wikidata.org/entity/Q406
5,http://www.wikidata.org/entity/Q125947998,Seniha Bedri Göknil,http://www.wikidata.org/entity/Q406

In [26]:
#SPARQL query to be executed
sparql.setQuery("""
PREFIX wd:    <http://www.wikidata.org/entity/>
PREFIX wdt:   <http://www.wikidata.org/prop/direct/>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?author ?authorName ?birthPlace
WHERE {
  ?author wdt:P106 wd:Q36180 ;          # has profession writer
          rdfs:label ?authorName ;
          wdt:P569 ?date ;
          wdt:P19 ?birthPlace .       # place of birth
          FILTER (lang(?authorName) = "en")
          FILTER ( ?date > "1990-01-01"^^xsd:dateTime )
          # ?birthPlace wdt:P31/wdt:P279* wd:Q515 . # place is an instance or a subclass of city

}
ORDER BY ?authorName
""")

sparql.setReturnFormat(JSON)   # Return format is JSON
results = sparql.query().convert()   # execute SPARQL query and write result to "results"

In [27]:
len(results['results']['bindings'])

3191

In [28]:
results_df = pd.json_normalize(results['results']['bindings'])
results_df[['author.value', 'authorName.value', 'birthPlace.value']]

,author.value,authorName.value,birthPlace.value
0,http://www.wikidata.org/entity/Q56414471,A'yat Khalili,http://www.wikidata.org/entity/Q11137
1,http://www.wikidata.org/entity/Q106395672,A.K. Blakemore,http://www.wikidata.org/entity/Q84
2,http://www.wikidata.org/entity/Q43423646,ARuFa,http://www.wikidata.org/entity/Q1490
3,http://www.wikidata.org/entity/Q125783603,Aamna Qureshi,http://www.wikidata.org/entity/Q18438
4,http://www.wikidata.org/entity/Q87419831,Aaqib Anjum Aafi,http://www.wikidata.org/entity/Q5299033
...,...,...,...
3186,http://www.wikidata.org/entity/Q121537124,Ľuboslav Priesečan,http://www.wikidata.org/entity/Q1070312
3187,http://www.wikidata.org/entity/Q110624165,Łukasz Barys,http://www.wikidata.org/entity/Q158589
3188,http://www.wikidata.org/entity/Q2607351,Şenay Düdek,http://www.wikidata.org/entity/Q35997
3189,http://www.wikidata.org/entity/Q95154721,Žaneta Voldánová,http://www.wikidata.org/entity/Q321778
3190,http://www.wikidata.org/entity/Q12223922,ʻAbd al-Wahhāb ibn Nāṣir Ṭurayrī,http://www.wikidata.org/entity/Q4116151