<a href="https://colab.research.google.com/github/UniVR-DH/DKR-course/blob/main/L17-WikiData/example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SPARQL Queries for WikiData

In [1]:
!pip install -q sparqlwrapper    #install SPARQLwrapper

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 615.4/615.4 kB 12.8 MB/s eta 0:00:00

In [3]:
from SPARQLWrapper import SPARQLWrapper, JSON, XML, RDF
import pandas as pd

In [6]:
sparql = SPARQLWrapper("https://query.wikidata.org/sparql") #determine SPARQL endpoint
sparql.setReturnFormat(JSON) #determine the output format

In [7]:
#SPARQL query to be executed
sparql.setQuery("""
PREFIX wd:    <http://www.wikidata.org/entity/>
PREFIX wdt:   <http://www.wikidata.org/prop/direct/>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?author ?authorName ?birthPlace
WHERE {
  ?author wdt:P31 wd:Q36180 ;          # instance of writer
          rdfs:label ?authorName ;
          wdt:P19 ?birthPlace .       # place of birth

  FILTER (lang(?authorName) = "en")
}
ORDER BY ?authorName
""")

sparql.setReturnFormat(JSON)   # Return format is JSON
results = sparql.query().convert()   # execute SPARQL query and write result to "results"

In [8]:
len(results['results']['bindings'])

1

In [9]:
results_df = pd.json_normalize(results['results']['bindings'])
results_df[['author.value', 'authorName.value', 'birthPlace.value']]

,author.value,authorName.value,birthPlace.value
0,http://www.wikidata.org/entity/Q125947998,Seniha Bedri Göknil,http://www.wikidata.org/entity/Q406

In [18]:
#SPARQL query to be executed
sparql.setQuery("""
PREFIX wd:    <http://www.wikidata.org/entity/>
PREFIX wdt:   <http://www.wikidata.org/prop/direct/>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?author ?authorName ?birthPlace
WHERE {
  ?author wdt:P106 wd:Q36180 ;          # has profession writer
          rdfs:label ?authorName ;
          wdt:P569 ?date ;
          wdt:P19 ?birthPlace .       # place of birth
  FILTER (lang(?authorName) = "en")
      FILTER ( ?date < "1700-01-01"^^xsd:dateTime )
}
ORDER BY ?authorName
""")

sparql.setReturnFormat(JSON)   # Return format is JSON
results = sparql.query().convert()   # execute SPARQL query and write result to "results"

In [19]:
len(results['results']['bindings'])

11003

In [20]:
results_df = pd.json_normalize(results['results']['bindings'])
results_df[['author.value', 'authorName.value', 'birthPlace.value']]

,author.value,authorName.value,birthPlace.value
0,http://www.wikidata.org/entity/Q12222083,'A'isha al-Ba'uniyya,http://www.wikidata.org/entity/Q3766
1,http://www.wikidata.org/entity/Q12222083,'A'isha al-Ba'uniyya,http://www.wikidata.org/entity/Q3766
2,http://www.wikidata.org/entity/Q543191,'Ali ibn al-'Abbas al-Majusi,http://www.wikidata.org/entity/Q170366
3,http://www.wikidata.org/entity/Q1951869,'Orfi Shirazi,http://www.wikidata.org/entity/Q6397066
4,http://www.wikidata.org/entity/Q1951869,'Orfi Shirazi,http://www.wikidata.org/entity/Q6397066
...,...,...,...
10998,http://www.wikidata.org/entity/Q426371,Ḥasan Ibn-Muḥammad al-Būrīnī,http://www.wikidata.org/entity/Q1132798
10999,http://www.wikidata.org/entity/Q4502475,Ḥusain Wāʿiẓ Kāšifī,http://www.wikidata.org/entity/Q765553
11000,http://www.wikidata.org/entity/Q94647656,Ḥāmid ibn ʻAlī ʻImādī,http://www.wikidata.org/entity/Q3766
11001,http://www.wikidata.org/entity/Q31299422,Ṣadr al-Shahīd,http://www.wikidata.org/entity/Q5764
11002,http://www.wikidata.org/entity/Q12220160,"Ṣafadī, Khalīl ibn Aybak",http://www.wikidata.org/entity/Q188336