<a href="https://colab.research.google.com/github/UniVR-DH/DKR-course/blob/main/L16-DBpedia/example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SPARQL Queries for DBpedia

In [1]:
!pip install -q sparqlwrapper    #install SPARQLwrapper

In [2]:
from SPARQLWrapper import SPARQLWrapper, JSON, XML, RDF
import pandas as pd

In [3]:
sparql = SPARQLWrapper("http://dbpedia.org/sparql") #determine SPARQL endpoint
sparql.setReturnFormat(JSON) #determine the output format

In [17]:
#SPARQL query to be executed
sparql.setQuery("""
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbo: <http://dbpedia.org/ontology/>

SELECT ?author ?authorName ?birthPlace
WHERE {
?author rdf:type dbo:Writer ;
        dbo:birthName  ?authorName ;
        dbo:birthPlace ?birthPlace .
 FILTER ((lang(?authorName)="en")) .

}

ORDER BY ?authorName
""")

sparql.setReturnFormat(JSON)   # Return format is JSON
results = sparql.query().convert()   # execute SPARQL query and write result to "results"

In [18]:
len(results['results']['bindings'])

10000

In [19]:
results_df = pd.json_normalize(results['results']['bindings'])
results_df[['author.value', 'authorName.value', 'birthPlace.value']]

,author.value,authorName.value,birthPlace.value
0,http://dbpedia.org/resource/Oscar_Wilde,,http://dbpedia.org/resource/Dublin
1,http://dbpedia.org/resource/Oscar_Wilde,,http://dbpedia.org/resource/Dublin
2,http://dbpedia.org/resource/Oscar_Wilde,,http://dbpedia.org/resource/Dublin
3,http://dbpedia.org/resource/Al-Hariri_of_Basra,,http://dbpedia.org/resource/Iraq
4,http://dbpedia.org/resource/Al-Hariri_of_Basra,,http://dbpedia.org/resource/Abbasid_Caliphate
...,...,...,...
9995,http://dbpedia.org/resource/Davis_Grubb,Davis Alexander Grubb,"http://dbpedia.org/resource/Moundsville,_West_..."
9996,http://dbpedia.org/resource/Davis_Grubb,Davis Alexander Grubb,"http://dbpedia.org/resource/Moundsville,_West_..."
9997,http://dbpedia.org/resource/Davis_Grubb,Davis Alexander Grubb,"http://dbpedia.org/resource/Moundsville,_West_..."
9998,http://dbpedia.org/resource/Darko_F._Ribnikar,Davorin Ribnikar,http://dbpedia.org/resource/Svilajnac
9999,http://dbpedia.org/resource/Darko_F._Ribnikar,Davorin Ribnikar,http://dbpedia.org/resource/Principality_of_Se...

In [20]:
#SPARQL query to be executed
sparql.setQuery("""
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbo: <http://dbpedia.org/ontology/>

SELECT DISTINCT  ?birthPlace
WHERE {
?author rdf:type dbo:Writer ;
        dbo:birthName  ?authorName ;
        dbo:birthPlace ?birthPlace .
 FILTER ((lang(?authorName)="en")) .

}
""")

sparql.setReturnFormat(JSON)   # Return format is JSON
results = sparql.query().convert()   # execute SPARQL query and write result to "results"

In [21]:
len(results['results']['bindings'])

6767

In [23]:
results_df = pd.json_normalize(results['results']['bindings'])
results_df[['birthPlace.value']]

                                    birthPlace.value
0              http://dbpedia.org/resource/Bhavnagar
1                  http://dbpedia.org/resource/Sihor
2             http://dbpedia.org/resource/Birmingham
3               http://dbpedia.org/resource/Tel_Aviv
4                 http://dbpedia.org/resource/London
...                                              ...
6762               http://dbpedia.org/resource/Lutsk
6763  http://dbpedia.org/resource/Nizamabad_district
6764         http://dbpedia.org/resource/Tillsonburg
6765            http://dbpedia.org/resource/Vallecas
6766               http://dbpedia.org/resource/Esher

[6767 rows x 1 columns]